# Site settings
title: Seawisp Hunter
email: shane.celis@seawisphunter.com
description: "Seawisp Hunter is a one-man operation by Shane Celis. He's an evolutionary robotics researcher turned game developer, making fun virtual robot toys. Follow him on twitter @shanecelis."
twitter_username: seawisphunter
twitter: "@shanecelis"
github_username:  shanecelis
baseurl: "/"
url: "http://seawisphunter.com"
post_ext: markdown
post_layout: post

# Build settings
markdown: redcarpet
permalink: pretty
#pygments: true
highlighter: pygments
redcarpet:
    extensions: ["no_intra_emphasis", "footnotes", "autolink", "strikethrough", "with_toc_data", "smart", "fenced_code_blocks"]
