# Site settings
title: Seawisp Hunter
email: shane.celis@seawisphunter.com
description: "I'm an evolutionary robotics researcher turned gamedev, making fun virtual robot toys that hint at artificial evolution (think: educational trojan horse)."
twitter_username: seawisphunter
github_username:  shanecelis
baseurl: "/"
url: "http://seawisphunter.com"

# Build settings
markdown: redcarpet
permalink: pretty
#pygments: true
highlighter: pygments
redcarpet:
    extensions: ["no_intra_emphasis", "footnotes", "autolink", "strikethrough", "with_toc_data", "smart", "fenced_code_blocks"]
